// This file is auto-generated by @hey-api/openapi-ts

export const SignInDtoSchema = {
  type: 'object',
  properties: {
    username: {
      type: 'string',
      description: '管理人员名称',
      example: 'admin',
    },
    password: {
      type: 'string',
      description: '密码',
      example: '123456',
    },
    email: {
      type: 'string',
      description: '邮箱',
      example: 'admin@email.com',
    },
  },
  required: ['password'],
} as const;

export const SexEnumSchema = {
  type: 'string',
  enum: ['Male', 'Female'],
  description: '性别',
} as const;

export const AdmintorStatusEnumSchema = {
  type: 'string',
  enum: ['Open', 'Close'],
  description: '状态',
} as const;

export const AdmintorsResultDtoSchema = {
  type: 'object',
  properties: {
    createdTime: {
      format: 'date-time',
      type: 'string',
      description: '创建日期',
      default: 1744459016991,
    },
    updatedTime: {
      format: 'date-time',
      type: 'string',
      description: '更新日期',
      default: 1744459016991,
    },
    username: {
      type: 'string',
      description: '管理人员名称',
      example: 'admin',
    },
    avatar: {
      type: 'string',
      description: '头像',
      example: '',
    },
    name: {
      type: 'string',
      description: '姓名',
      example: '',
    },
    roles: {
      description: '角色',
      example: [],
      type: 'array',
      items: {
        type: 'string',
      },
    },
    sex: {
      description: '性别',
      example: 'Male',
      allOf: [
        {
          $ref: '#/components/schemas/SexEnum',
        },
      ],
    },
    phone: {
      type: 'string',
      description: '电话号码',
      example: '',
    },
    email: {
      type: 'string',
      description: '邮箱',
      example: '',
    },
    status: {
      description: '状态',
      example: 'Open',
      allOf: [
        {
          $ref: '#/components/schemas/AdmintorStatusEnum',
        },
      ],
    },
    _id: {
      type: 'string',
      description: '唯一值',
    },
  },
  required: [
    'createdTime',
    'updatedTime',
    'username',
    'roles',
    'email',
    'status',
    '_id',
  ],
} as const;

export const LoginSuccessResultDtoSchema = {
  type: 'object',
  properties: {
    access_token: {
      type: 'string',
      example: 'token123456',
    },
    userInfo: {
      example: {
        createdTime: '1743413281187',
        updatedTime: '1743413281187',
        username: 'admin',
        avatar: '',
        name: '',
        roles: [],
        sex: 'Male',
        phone: '',
        email: '',
        status: 'Open',
        _id: 'string',
      },
      allOf: [
        {
          $ref: '#/components/schemas/AdmintorsResultDto',
        },
      ],
    },
    menus: {
      example: [],
      type: 'array',
      items: {
        type: 'string',
      },
    },
  },
  required: ['access_token', 'userInfo', 'menus'],
} as const;

export const ErrorResultDtoSchema = {
  type: 'object',
  properties: {
    message: {
      type: 'string',
      description: '错误信息',
    },
    statusCode: {
      type: 'number',
      description: '错误码',
    },
  },
  required: ['message', 'statusCode'],
} as const;

export const AdmintorsCreateBodyDtoSchema = {
  type: 'object',
  properties: {
    username: {
      type: 'string',
      description: '管理人员名称',
      example: 'admin',
    },
    password: {
      type: 'string',
      description: '密码',
      example: '123456',
    },
    roles: {
      description: '角色',
      example: [],
      type: 'array',
      items: {
        type: 'string',
      },
    },
  },
  required: ['username', 'password', 'roles'],
} as const;

export const DeleteIdsDtoSchema = {
  type: 'object',
  properties: {
    ids: {
      description: '删除Id列表',
      type: 'array',
      items: {
        type: 'string',
      },
    },
  },
  required: ['ids'],
} as const;

export const IntersectionUpdateResDtoDeleteResDtoSchema = {
  type: 'object',
  properties: {
    acknowledged: {
      type: 'boolean',
      description: '是否成功',
    },
    modifiedCount: {
      type: 'number',
      description: '更新数量',
    },
    upsertedId: {
      type: 'string',
      description: '更新插入id',
    },
    upsertedCount: {
      type: 'number',
      description: '更新插入数量',
    },
    matchedCount: {
      type: 'number',
      description: '符合更新条件的数量',
    },
    deletedCount: {
      type: 'number',
      description: '匹配数量',
    },
  },
  required: ['acknowledged'],
} as const;

export const AdmintorsUpdateDtoSchema = {
  type: 'object',
  properties: {
    username: {
      type: 'string',
      description: '管理人员名称',
      example: 'admin',
    },
    avatar: {
      type: 'string',
      description: '头像',
      example: '',
    },
    name: {
      type: 'string',
      description: '姓名',
      example: '',
    },
    roles: {
      description: '角色',
      example: [],
      type: 'array',
      items: {
        type: 'string',
      },
    },
    sex: {
      description: '性别',
      example: 'Male',
      allOf: [
        {
          $ref: '#/components/schemas/SexEnum',
        },
      ],
    },
    phone: {
      type: 'string',
      description: '电话号码',
      example: '',
    },
    email: {
      type: 'string',
      description: '邮箱',
      example: '',
    },
    status: {
      description: '状态',
      example: 'Open',
      allOf: [
        {
          $ref: '#/components/schemas/AdmintorStatusEnum',
        },
      ],
    },
  },
} as const;

export const UpdateResDtoSchema = {
  type: 'object',
  properties: {
    acknowledged: {
      type: 'boolean',
      description: '是否成功',
    },
    modifiedCount: {
      type: 'number',
      description: '更新数量',
    },
    upsertedId: {
      type: 'string',
      description: '更新插入id',
    },
    upsertedCount: {
      type: 'number',
      description: '更新插入数量',
    },
    matchedCount: {
      type: 'number',
      description: '符合更新条件的数量',
    },
  },
  required: ['acknowledged'],
} as const;

export const DateTimeRangeDtoSchema = {
  type: 'object',
  properties: {
    createdTime: {
      type: 'array',
      description: '创建时间范围',
      readOnly: true,
      minLength: 2,
      maxLength: 2,
      items: {
        readOnly: true,
        type: 'string',
        format: 'date-time',
      },
    },
    updatedTime: {
      type: 'array',
      description: '更新时间范围',
      readOnly: true,
      minLength: 2,
      maxLength: 2,
      items: {
        readOnly: true,
        type: 'string',
        format: 'date-time',
      },
    },
  },
} as const;

export const PickTypeClassSchema = {
  type: 'object',
  properties: {
    username: {
      type: 'string',
      description: '管理人员名称',
      example: 'admin',
    },
    name: {
      type: 'string',
      description: '姓名',
      example: '',
    },
    email: {
      type: 'string',
      description: '邮箱',
      example: '',
    },
  },
  required: ['username', 'email'],
} as const;

export const AdmintorsFilterDtoSchema = {
  type: 'object',
  properties: {
    avatar: {
      type: 'string',
      description: '头像',
      example: '',
    },
    roles: {
      description: '角色',
      example: [],
      type: 'array',
      items: {
        type: 'string',
      },
    },
    sex: {
      description: '性别',
      example: 'Male',
      allOf: [
        {
          $ref: '#/components/schemas/SexEnum',
        },
      ],
    },
    phone: {
      type: 'string',
      description: '电话号码',
      example: '',
    },
    status: {
      description: '状态',
      example: 'Open',
      allOf: [
        {
          $ref: '#/components/schemas/AdmintorStatusEnum',
        },
      ],
    },
    dateTimeRange: {
      description: '时间范围',
      allOf: [
        {
          $ref: '#/components/schemas/DateTimeRangeDto',
        },
      ],
    },
    fuzzyFields: {
      description: '模糊查询字段',
      allOf: [
        {
          $ref: '#/components/schemas/PickTypeClass',
        },
      ],
    },
  },
} as const;

export const RolesResultDtoSchema = {
  type: 'object',
  properties: {
    createdTime: {
      format: 'date-time',
      type: 'string',
      description: '创建日期',
      default: 1744459016991,
    },
    updatedTime: {
      format: 'date-time',
      type: 'string',
      description: '更新日期',
      default: 1744459016991,
    },
    name: {
      type: 'string',
      description: '角色名称',
      example: 'role',
    },
    description: {
      type: 'string',
      description: '角色名称',
      example: '我是角色描述',
    },
    icon: {
      type: 'string',
      description: '图标',
      example: '',
    },
    menus: {
      description: '菜单',
      example: [],
      type: 'array',
      items: {
        type: 'string',
      },
    },
    _id: {
      type: 'string',
      description: '唯一值',
    },
  },
  required: ['createdTime', 'updatedTime', 'name', 'menus', '_id'],
} as const;

export const AdmintorsPageItemDtoSchema = {
  type: 'object',
  properties: {
    createdTime: {
      format: 'date-time',
      type: 'string',
      description: '创建日期',
      default: 1744459016991,
    },
    updatedTime: {
      format: 'date-time',
      type: 'string',
      description: '更新日期',
      default: 1744459016991,
    },
    username: {
      type: 'string',
      description: '管理人员名称',
      example: 'admin',
    },
    avatar: {
      type: 'string',
      description: '头像',
      example: '',
    },
    name: {
      type: 'string',
      description: '姓名',
      example: '',
    },
    sex: {
      description: '性别',
      example: 'Male',
      allOf: [
        {
          $ref: '#/components/schemas/SexEnum',
        },
      ],
    },
    phone: {
      type: 'string',
      description: '电话号码',
      example: '',
    },
    email: {
      type: 'string',
      description: '邮箱',
      example: '',
    },
    status: {
      description: '状态',
      example: 'Open',
      allOf: [
        {
          $ref: '#/components/schemas/AdmintorStatusEnum',
        },
      ],
    },
    _id: {
      type: 'string',
      description: '唯一值',
    },
    roles: {
      description: '角色列表',
      type: 'array',
      items: {
        $ref: '#/components/schemas/RolesResultDto',
      },
    },
  },
  required: [
    'createdTime',
    'updatedTime',
    'username',
    'email',
    'status',
    '_id',
    'roles',
  ],
} as const;

export const AdmintorPaginationResultDtoSchema = {
  type: 'object',
  properties: {
    pageNo: {
      type: 'number',
      description: '当前页面',
      minimum: 1,
      example: 1,
    },
    pageSize: {
      type: 'number',
      description: '分页大小',
      minimum: 1,
      example: 10,
    },
    total: {
      type: 'number',
      description: '所有数量',
      example: 1,
    },
    list: {
      description: '所有数量',
      type: 'array',
      items: {
        $ref: '#/components/schemas/AdmintorsPageItemDto',
      },
    },
  },
  required: ['pageNo', 'pageSize', 'total', 'list'],
} as const;

export const RoleCreateBodyDtoSchema = {
  type: 'object',
  properties: {
    name: {
      type: 'string',
      description: '角色名称',
      example: 'role',
    },
    description: {
      type: 'string',
      description: '角色名称',
      example: '我是角色描述',
    },
    icon: {
      type: 'string',
      description: '图标',
      example: '',
    },
    menus: {
      description: '菜单',
      example: [],
      type: 'array',
      items: {
        type: 'string',
      },
    },
  },
  required: ['name', 'menus'],
} as const;

export const RolesUpdateDtoSchema = {
  type: 'object',
  properties: {
    updatedTime: {
      format: 'date-time',
      type: 'string',
      description: '更新日期',
      default: 1744459016991,
    },
    name: {
      type: 'string',
      description: '角色名称',
      example: 'role',
    },
    description: {
      type: 'string',
      description: '角色名称',
      example: '我是角色描述',
    },
    icon: {
      type: 'string',
      description: '图标',
      example: '',
    },
    menus: {
      description: '菜单',
      example: [],
      type: 'array',
      items: {
        type: 'string',
      },
    },
  },
} as const;

export const RolesQueryFilterDtoSchema = {
  type: 'object',
  properties: {
    createdTime: {
      format: 'date-time',
      type: 'string',
      description: '创建日期',
      default: 1744459016991,
    },
    updatedTime: {
      format: 'date-time',
      type: 'string',
      description: '更新日期',
      default: 1744459016991,
    },
    name: {
      type: 'string',
      description: '角色名称',
      example: 'role',
    },
    description: {
      type: 'string',
      description: '角色名称',
      example: '我是角色描述',
    },
    icon: {
      type: 'string',
      description: '图标',
      example: '',
    },
    menus: {
      description: '菜单',
      example: [],
      type: 'array',
      items: {
        type: 'string',
      },
    },
  },
} as const;

export const RoleQueryPaginationResultDtoSchema = {
  type: 'object',
  properties: {
    pageNo: {
      type: 'number',
      description: '当前页面',
      minimum: 1,
      example: 1,
    },
    pageSize: {
      type: 'number',
      description: '分页大小',
      minimum: 1,
      example: 10,
    },
    total: {
      type: 'number',
      description: '所有数量',
      example: 1,
    },
    list: {
      description: '所有数量',
      type: 'array',
      items: {
        $ref: '#/components/schemas/RolesResultDto',
      },
    },
  },
  required: ['pageNo', 'pageSize', 'total', 'list'],
} as const;

export const MenuTypeEnumSchema = {
  type: 'string',
  enum: ['Directory', 'Page', 'FunctionArea'],
  description: '菜单类型',
} as const;

export const MenusCreateBodyDtoSchema = {
  type: 'object',
  properties: {
    name: {
      type: 'string',
      description: '菜单名称',
      example: 'menuName',
    },
    uniqueKey: {
      type: 'string',
      description: '菜单唯一键',
      example: 'uniqueKey',
    },
    description: {
      type: 'string',
      description: '菜单名称',
      example: '我是菜单描述',
    },
    path: {
      type: 'string',
      description: '菜单路径',
      example: '',
    },
    sort: {
      type: 'number',
      description: '用作菜单排序',
      example: 0,
    },
    icon: {
      type: 'string',
      description: '图标',
      example: '',
    },
    parent: {
      type: 'string',
      description: '图标',
      example: '',
    },
    menuType: {
      description: '菜单类型',
      example: 'Directory',
      allOf: [
        {
          $ref: '#/components/schemas/MenuTypeEnum',
        },
      ],
    },
    isHide: {
      type: 'boolean',
      description: '是否隐藏',
    },
  },
  required: ['name', 'sort', 'menuType', 'isHide'],
} as const;

export const MenusResultDtoSchema = {
  type: 'object',
  properties: {
    createdTime: {
      format: 'date-time',
      type: 'string',
      description: '创建日期',
      default: 1744459016991,
    },
    updatedTime: {
      format: 'date-time',
      type: 'string',
      description: '更新日期',
      default: 1744459016991,
    },
    name: {
      type: 'string',
      description: '菜单名称',
      example: 'menuName',
    },
    uniqueKey: {
      type: 'string',
      description: '菜单唯一键',
      example: 'uniqueKey',
    },
    description: {
      type: 'string',
      description: '菜单名称',
      example: '我是菜单描述',
    },
    path: {
      type: 'string',
      description: '菜单路径',
      example: '',
    },
    sort: {
      type: 'number',
      description: '用作菜单排序',
      example: 0,
    },
    icon: {
      type: 'string',
      description: '图标',
      example: '',
    },
    parent: {
      type: 'string',
      description: '图标',
      example: '',
    },
    menuType: {
      description: '菜单类型',
      example: 'Directory',
      allOf: [
        {
          $ref: '#/components/schemas/MenuTypeEnum',
        },
      ],
    },
    isHide: {
      type: 'boolean',
      description: '是否隐藏',
    },
    _id: {
      type: 'string',
      description: '唯一值',
    },
  },
  required: [
    'createdTime',
    'updatedTime',
    'name',
    'sort',
    'menuType',
    'isHide',
    '_id',
  ],
} as const;

export const MenusUpdateDtoSchema = {
  type: 'object',
  properties: {
    updatedTime: {
      format: 'date-time',
      type: 'string',
      description: '更新日期',
      default: 1744459016991,
    },
    name: {
      type: 'string',
      description: '菜单名称',
      example: 'menuName',
    },
    uniqueKey: {
      type: 'string',
      description: '菜单唯一键',
      example: 'uniqueKey',
    },
    description: {
      type: 'string',
      description: '菜单名称',
      example: '我是菜单描述',
    },
    path: {
      type: 'string',
      description: '菜单路径',
      example: '',
    },
    sort: {
      type: 'number',
      description: '用作菜单排序',
      example: 0,
    },
    icon: {
      type: 'string',
      description: '图标',
      example: '',
    },
    parent: {
      type: 'string',
      description: '图标',
      example: '',
    },
    menuType: {
      description: '菜单类型',
      example: 'Directory',
      allOf: [
        {
          $ref: '#/components/schemas/MenuTypeEnum',
        },
      ],
    },
    isHide: {
      type: 'boolean',
      description: '是否隐藏',
    },
  },
} as const;

export const TreeMenuDataDtoSchema = {
  type: 'object',
  properties: {
    deletedTime: {
      format: 'date-time',
      type: 'string',
      description: '删除时间',
      default: '',
    },
    createdTime: {
      format: 'date-time',
      type: 'string',
      description: '创建日期',
      default: 1744459016991,
    },
    updatedTime: {
      format: 'date-time',
      type: 'string',
      description: '更新日期',
      default: 1744459016991,
    },
    name: {
      type: 'string',
      description: '菜单名称',
      example: 'menuName',
    },
    uniqueKey: {
      type: 'string',
      description: '菜单唯一键',
      example: 'uniqueKey',
    },
    description: {
      type: 'string',
      description: '菜单名称',
      example: '我是菜单描述',
    },
    path: {
      type: 'string',
      description: '菜单路径',
      example: '',
    },
    sort: {
      type: 'number',
      description: '用作菜单排序',
      example: 0,
    },
    icon: {
      type: 'string',
      description: '图标',
      example: '',
    },
    parent: {
      type: 'string',
      description: '图标',
      example: '',
    },
    menuType: {
      description: '菜单类型',
      example: 'Directory',
      allOf: [
        {
          $ref: '#/components/schemas/MenuTypeEnum',
        },
      ],
    },
    isHide: {
      type: 'boolean',
      description: '是否隐藏',
    },
    _id: {
      type: 'string',
      description: '唯一值',
    },
    children: {
      description: '唯一值',
      examples: [],
      type: 'array',
      items: {
        $ref: '#/components/schemas/TreeMenuDataDto',
      },
    },
  },
  required: [
    'createdTime',
    'updatedTime',
    'name',
    'sort',
    'menuType',
    'isHide',
    '_id',
    'children',
  ],
} as const;

export const MenusQueryDtoSchema = {
  type: 'object',
  properties: {
    createdTime: {
      format: 'date-time',
      type: 'string',
      description: '创建日期',
      default: 1744459016991,
    },
    updatedTime: {
      format: 'date-time',
      type: 'string',
      description: '更新日期',
      default: 1744459016991,
    },
    name: {
      type: 'string',
      description: '菜单名称',
      example: 'menuName',
    },
    uniqueKey: {
      type: 'string',
      description: '菜单唯一键',
      example: 'uniqueKey',
    },
    description: {
      type: 'string',
      description: '菜单名称',
      example: '我是菜单描述',
    },
    path: {
      type: 'string',
      description: '菜单路径',
      example: '',
    },
    sort: {
      type: 'number',
      description: '用作菜单排序',
      example: 0,
    },
    icon: {
      type: 'string',
      description: '图标',
      example: '',
    },
    parent: {
      type: 'string',
      description: '图标',
      example: '',
    },
    menuType: {
      description: '菜单类型',
      example: 'Directory',
      allOf: [
        {
          $ref: '#/components/schemas/MenuTypeEnum',
        },
      ],
    },
    isHide: {
      type: 'boolean',
      description: '是否隐藏',
    },
  },
} as const;

export const FileUploadDtoSchema = {
  type: 'object',
  properties: {
    file: {
      type: 'string',
      format: 'binary',
    },
  },
  required: ['file'],
} as const;

export const FileUploadSuccessResultDtoSchema = {
  type: 'object',
  properties: {
    url: {
      type: 'string',
      description: '图片地址',
    },
  },
  required: ['url'],
} as const;

export const FilesUploadDtoSchema = {
  type: 'object',
  properties: {
    files: {
      type: 'array',
      items: {
        type: 'string',
        format: 'binary',
      },
    },
  },
  required: ['files'],
} as const;

export const FilesQueryFilterDtoSchema = {
  type: 'object',
  properties: {
    mimetype: {
      type: 'string',
      description: '文件类型',
      example: 'fileName',
    },
    size: {
      type: 'number',
      description: '文件大小',
      example: 1024,
    },
    path: {
      type: 'string',
      description: '文件路径',
      example: '/file/fileName.png',
    },
    dateTimeRange: {
      description: '时间范围',
      allOf: [
        {
          $ref: '#/components/schemas/DateTimeRangeDto',
        },
      ],
    },
    fuzzyFields: {
      description: '模糊查询字段',
      allOf: [
        {
          $ref: '#/components/schemas/PickTypeClass',
        },
      ],
    },
  },
} as const;

export const FilesResultDtoSchema = {
  type: 'object',
  properties: {
    createdTime: {
      format: 'date-time',
      type: 'string',
      description: '创建日期',
      default: 1744459016991,
    },
    updatedTime: {
      format: 'date-time',
      type: 'string',
      description: '更新日期',
      default: 1744459016991,
    },
    originalname: {
      type: 'string',
      description: '原始文件名',
      example: 'image/jpeg',
    },
    uniquedName: {
      type: 'string',
      description: '唯一文件名',
      example: 'uniqueName',
    },
    mimetype: {
      type: 'string',
      description: '文件类型',
      example: 'fileName',
    },
    size: {
      type: 'number',
      description: '文件大小',
      example: 1024,
    },
    path: {
      type: 'string',
      description: '文件路径',
      example: '/file/fileName.png',
    },
    _id: {
      type: 'string',
      description: '唯一值',
    },
  },
  required: [
    'createdTime',
    'updatedTime',
    'originalname',
    'uniquedName',
    'mimetype',
    'size',
    'path',
    '_id',
  ],
} as const;

export const FilesPaginationResultDtoSchema = {
  type: 'object',
  properties: {
    pageNo: {
      type: 'number',
      description: '当前页面',
      minimum: 1,
      example: 1,
    },
    pageSize: {
      type: 'number',
      description: '分页大小',
      minimum: 1,
      example: 10,
    },
    total: {
      type: 'number',
      description: '所有数量',
      example: 1,
    },
    list: {
      description: '所有数量',
      type: 'array',
      items: {
        $ref: '#/components/schemas/FilesResultDto',
      },
    },
  },
  required: ['pageNo', 'pageSize', 'total', 'list'],
} as const;

export const FilesBatchDeleteDtoSchema = {
  type: 'object',
  properties: {
    fileList: {
      description: '文件列表',
      type: 'array',
      items: {
        $ref: '#/components/schemas/FilesResultDto',
      },
    },
  },
  required: ['fileList'],
} as const;

export const FileInfoSchema = {
  type: 'object',
  properties: {
    path: {
      type: 'string',
      description: '文件路径',
      example: '/file/fileName.png',
    },
    _id: {
      type: 'string',
      description: '唯一值',
    },
  },
  required: ['path', '_id'],
} as const;

export const FileUpdateDtoSchema = {
  type: 'object',
  properties: {
    file: {
      type: 'string',
      format: 'binary',
    },
    fileInfo: {
      format: 'binary',
      allOf: [
        {
          $ref: '#/components/schemas/FileInfo',
        },
      ],
    },
  },
  required: ['file', 'fileInfo'],
} as const;
